### ISSUE TITLE
release on hex.pm

### ISSUE THREAD

**Issue by benoitc** [jlouis/safetyvalve#13]
Would be cool to have the latest release on hex :)

**Comment by jlouis** [comment]
Yes, I agree.

My `hex.pm` work is currently lacking a bit and I also need it for other work, so it will be worth it to look into. Currently we only depend on `lager` and that is also available in `hex.pm`, so it shouldn't be that hard to make the code work like it should.

**Comment by jadeallenx** [comment]
Bump on this issue :)

**Comment by jlouis** [comment]
This one is also getting done tomorrow :)

**Comment by jadeallenx** [comment]
Thanks!

**Comment by jlouis** [comment]
This should have happened as well now:

https://hex.pm/packages/safetyvalve

Now to figure out if I'm missing some packages there :)

**Comment by jadeallenx** [comment]
Thanks!!
