### ISSUE TITLE
sv_queue process exit on ets:lookup_element

### ISSUE THREAD

**Issue by lrascao** [jlouis/safetyvalve#5]
Feels like this is probably related with #2, i'm running the following simple test, (spawn 5 concurrent processes, each has flow controlled from a very restrictive queue)  :
`application:set_env(safetyvalve, queues, [{queue,
    [{queue_type, sv_queue_ets},{rate, 1},{hz, 1000},{token_limit, 1},{size, 1},{concurrency, 1}]}]).
application:ensure_all_started(safetyvalve).
[begin spawn(fun() -> Result = sv:run(queue, fun() -> a end),io:format("result (~p): ~p~n", [calendar:now_to_datetime(erlang:now()), Result]) end) end || N <- lists:seq(0,5)].`

most times what happens is the first process returns `ok` and the others `{error, queue_full}`, the gen_server sv_queue then crashes with
`gen_server queue terminated with reason: bad argument in call to ets:lookup_element(24595, #Ref<0.0.0.140>, 2) in sv_queue:handle_info/2`

first of all, is this something we want to fix? a simple solution would be catch'ing the ets lookup and silently ignoring the exception

**Comment by jlouis** [comment]
That sounds like a bug indeed. I'd have to look into what happens on the ETS table to fix it. My logic would be that one gets in to run, one gets queued and returns one second later. The latter 3 gets rejected. But it is clearly not what you are seeing.

**Comment by jlouis** [comment]
The problem is due to an invariant being broken in the code. I have a fix for this cooking currently. The larger part of the problem is that the current QuickCheck model doesn't test for this case either, which it definitely should, so that is another part of the problem.

**Comment by jlouis** [comment]
Oh, it is *sinister*. What happens in the QC model is that it realizes that the call `sv:ask(?Q, sv:timestamp())` will not block. So it runs this task in the main QC process, which never terminates while the test is ongoing. Thus it doesn't manage to capture this bug as a result.

**Comment by jlouis** [comment]
I've pushed a fix to master, please test if this solves your problem.

**Comment by lrascao** [comment]
yep, that did the trick
thanks!
